### ISSUE TITLE
Feature-proof gvsbuild.cmd.

### ISSUE THREAD

**Issue by mhertz** [petersasi/deluge2-win-build#5]
Whenever gvsbuild themselves updates gtk3 next time, then the patching I added will fail, meaning that new fourth-coming gtk3 updates will not be auto-built anymore and the patch for better readability of win32 theme also not applied.

The following I added in my script to negate that, so if interested then here's instructions for inspiration:

Ditch the gtk3.patch file in 'C:\deluge2\gvsbuild-build' folder, and instead
download linked zip and extract the win32.patch from it into before mentioned folder. Lastly replace the line that patches with  gtk3.patch with instead:
````
copy "%~dp0win32.patch" patches\gtk3-24
sed -i 's/gtk3_24(Tarball/gtk3_24(GitRepo/' gvsbuild\projects.py
sed -i "/prj_dir='gtk3-24',/{n;N;d}" gvsbuild\projects.py
sed -i "/prj_dir='gtk3-24',/a\            repo_url = 'https:\/\/gitlab.gnome.org\/GNOME\/gtk.git',\n            fetch_submodules = False,\n            tag = 'gtk-3-24'," gvsbuild\projects.py
sed -i "/'gtk_update_icon_cache.patch',/a\                'win32.patch'," gvsbuild\projects.py
````
https://gofile.io/d/HbRXCZ

**Comment by petersasi** [comment]
Thanks I have replaced these lines and verified them, they work well.
Another note: now the wingtk gvsbuild seems to run the vcvars.bat so I have commented it out of the script.

However: up till yesterday my gvsbuild workied fine with 3.24.21 and also 3.24.23, today it fails for me (both with and without the vcvars.bat): is it something they just committed, does it fail for you too, or it is a problem in my setup only?

**Comment by mhertz** [comment]
Until proper fix, then on my end I just reverted the gvsbuild failing commit(glib 2.66 update), so right after this line:

"cd C:\gtk-build\github\gvsbuild"

I added this line:

````
curl https://github.com/wingtk/gvsbuild/commit/7a854acb4189007161fa5cae593bfe5600601ff4.patch | patch.exe -R -p1
````

**Comment by petersasi** [comment]
Thanks, Maybe we should also submit an issue of the Windows build breakage? :)

**Comment by mhertz** [comment]
Yes, I was looking quickly little around, and for now just saw on glib issues bugtracker a poster having issues with glib 2.66 on windows with py3.8.5 but about loading propperly, and so seemed unrelated.

I have gathered gvsbuild logs/errors for only building glib solely, to make clean report, as was thinking the same. I'll post on the gvsbuild bugtracker shortly.

**Comment by mhertz** [comment]
Hmm, messed little around first, before submitting ticket. Anyway, it's a patch that fails applying for glib, added by gvsbuild 6 months ago, and when patching gvsbuild to omit that patch, then builds fine with the newly updated glib 2.66 and gtk3 etc.

I've made ticket now, about if that patch should be removed or adapted, but untill getting answer for that, then in addition to previous workaround previously posted of reverting glib, then following can be used as another workaround(or potential actual fix), if wanted, for omiting that failing patch of glib:

Delete the previous workaround from this thread here, and instead apply, right after this line:

"cd C:\gtk-build\github\gvsbuild"

These two lines:
```
sed -i '/AccessViolation-.patch/d' gvsbuild\projects.py
sed -i "s/directory.patch',/directory.patch'],/" gvsbuild\projects.py
```
Tested working in initial build + both deluge builds run with said gtk3 stack produced.

gvsbuild ticket: https://github.com/wingtk/gvsbuild/issues/394

**Comment by petersasi** [comment]
I think they reverted that line already, so I am just testing the build without any new patching to see if it okay, thanks for reporting and thanks for testing.
Not on this topic but still gvsbuild: to you have any idea how to add `/GL` to the MSVC command lines and `/LTCG` to the linker command lines? I have noticed that more and more linux distros now rebuild their packages using LTO so I was wondering if we could try and turn on Whole Program Optimization which is the MSVC version of LTO for GTK, Boost and libtorrent...

**Comment by petersasi** [comment]
I don't even know if the whole build uses meson and ninja or if some project use CMake or another build systems...

**Comment by petersasi** [comment]
I did add an issue to that project to initiate this at least: https://github.com/wingtk/gvsbuild/issues/395

**Comment by mhertz** [comment]
Sorry I don't know anything about that unfortunetly.

**Comment by mhertz** [comment]
Together with the gvsbuild source, you can also maybe cross-reference with the official windows gtk-stack building docs: https://wiki.gnome.org/Projects/GTK/Win32/MSVCCompilationOfGTKStack

In one of the components bzip2 if I remember right, they specify add a few build-options e.g -GL though bz2 is optional for freetype and I don't think gvsbuild even has support for building bzip2, but could be wrong and just quick peek at source. 

For Cairo, they state don't because of whole program optimization issue with either Cairo or msvc, though it's listed as old issue from 2014, but page is up2date with . E.g msvc 2019, and last edited a couple months ago only, I saw.

I quickly made other search, where one had issues with whole-program-optimization in a part of gtk stack, and it was eventually fixed, but initially at least one of the devs was pretty abrupt and just stated to not try use non-working switches really.

Anyway, since one of the components in the official docs is stated to enable it specifically, then kinda sound like they already have messed around with it, atleast somewhat.
